### ISSUE TITLE
Equality

### ISSUE THREAD

**Issue by j-Myles** [danielgaooooo/a1p2#10]
For the toString() tests

    t_true(strcmp(empty->to_string(), ""));
    t_true(strcmp(key1->to_string(), "Key Bob"));
    t_true(strcmp(key2->to_string(), "Key Ann"));
    t_true(strcmp(emptyObj->to_string(), ""));
    t_true(strcmp(obj1->to_string(), "Obj Bob"));
    t_true(strcmp(obj2->to_string(), "Obj Ann"));

These are all correct, however your t_true() method fails when given an input of 0. Since strcmp gives an output of 0 when two char* are identical,  the methods should reflect this with t_true(strcmp(val1, val2) == 0)

**Comment by danielgaooooo** [comment]
done
