### ISSUE TITLE
Testing using the hash function

### ISSUE THREAD

**Issue by obrahme** [danielgaooooo/a1p2#3]
If you hash identical maps, the values will still be different. Each hash is a unique value, so statements like this are invalid:
t_true(emptyMap->hash() == emptyMap->hash());

Please fix statements like this in your test.

**Comment by danielgaooooo** [comment]
I've actually never heard of this, could you point me to a source?

**Comment by yeungbri** [comment]
If two objects are semantically equal they should produce the same hash? Sorry if this was not clear in our documentation.

**Comment by obrahme** [comment]
This is correct, I had thought that hashing different objects regardless of being semantically equal would return a different hash.
