### ISSUE TITLE
toString

### ISSUE THREAD

**Issue by j-Myles** [danielgaooooo/a1p2#5]
Why do you include a complete method for converting maps to string formatted objects. In ordinary cases where one maps a String to another String this isn't a problem, but when mapping to other objects, such as floating point numbers, the method will be incorrect based on non-uniform constraints such as float precision. Furthermore this doesnt even account for future object structures which we can easily end up implementing in hashmaps that have no easy tostring() implementation, such as unordered lists, or even object structures that don't have string implementations such as a Furniture : Class or something like that. Can we please just have the tostring() method and its assorted test removed altogether considering it isnt included as a neccessary method in the assignment specification

**Comment by danielgaooooo** [comment]
ya

**Comment by danielgaooooo** [comment]
done and closed
