### ISSUE TITLE
concat()

### ISSUE THREAD

**Issue by j-Myles** [danielgaooooo/a1p2#6]
In your testString() method, for your 5th test, 

    t_true(bob->concat(joe)->equals(bobAnnJoeAnnCopy));

you operate based on the assumption that the earlier concat tests modify bob and joe. This is INCORRECT, as per based on your own specification concat: 
  
/* Creates a new String by combining two existing Strings */

A simple fix would be: 

    t_true(bobAnnCopy->concat(joeAnnCopy)->equals(bobAnnJoeAnnCopy));

**Comment by danielgaooooo** [comment]
ya, done and closed
