### ISSUE TITLE
testEquals

### ISSUE THREAD

**Issue by j-Myles** [danielgaooooo/a1p2#7]
There are a few mistakes here that look like simple copy/paste errors but I may be wrong so let me know. 

void testEquals() {
	String* empty = new String();
	String* key1 = new String("Key Bob");
	String* key2 = new String("Key Joe");
	String* key3 = new String("Key Ann");
	t_true(empty->equals(empty)); 
	t_false(empty->equals(key1));
	t_true(key1->equals(key2)); // Incorrect, key1 (Key bob) does not equal key2 (Key Joe)
	t_true(key2->equals(key1)); // Incorrect same reason as above ^
	t_false(key1->equals(key3));
	t_false(key3->equals(key1));
	t_true(key1->equals(key1));

**Comment by danielgaooooo** [comment]
done, closed
