### ISSUE TITLE
testMapKeys

### ISSUE THREAD

**Issue by j-Myles** [danielgaooooo/a1p2#8]
In your test map function you specifically have these test cases

    t_true(emptyMap->getKeys() == nullptr);
    t_true(map2->getKeys() == map2Keys);
    t_true(map3->getKeys() == map3Keys);
    t_true(mapInMap->getKeys() == mapInMapKeys);

I do not quite understand how you expect us to be able to implement this in the way you describe. The nullptr case aside as it is simple to implement, the only way for the other tests to pass is to have direct pointer comparison. Not only does this mean our getKeys() function can only output String**, instead of optimally outputting Object** which most of us likely have as our data representation, but the == operator requires that they point to the EXACT same memory location. It's IMPOSSIBLE for our getKeys() function to point to the exact same memory location as your map2Keys which you created IN the test function.

**Comment by danielgaooooo** [comment]
yee
